// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Realm, RealmTableId } from "./tables/Realm.sol";
import { Token, TokenTableId } from "./tables/Token.sol";
import { Chamber, ChamberData, ChamberTableId } from "./tables/Chamber.sol";
import { ChamberMetadata, ChamberMetadataData, ChamberMetadataTableId } from "./tables/ChamberMetadata.sol";
