// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("Tiles")));
bytes32 constant TilesTableId = _tableId;

struct TilesData {
  uint256 coord;
  uint8 index;
  uint8 tileType;
  uint8 tileX;
  uint8 tileY;
  uint8 gridX;
  uint8 gridY;
}

library Tiles {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](7);
    _schema[0] = SchemaType.UINT256;
    _schema[1] = SchemaType.UINT8;
    _schema[2] = SchemaType.UINT8;
    _schema[3] = SchemaType.UINT8;
    _schema[4] = SchemaType.UINT8;
    _schema[5] = SchemaType.UINT8;
    _schema[6] = SchemaType.UINT8;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](7);
    _fieldNames[0] = "coord";
    _fieldNames[1] = "index";
    _fieldNames[2] = "tileType";
    _fieldNames[3] = "tileX";
    _fieldNames[4] = "tileY";
    _fieldNames[5] = "gridX";
    _fieldNames[6] = "gridY";
    return ("Tiles", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get coord */
  function getCoord(bytes32 key) internal view returns (uint256 coord) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get coord (using the specified store) */
  function getCoord(IStore _store, bytes32 key) internal view returns (uint256 coord) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set coord */
  function setCoord(bytes32 key, uint256 coord) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((coord)));
  }

  /** Set coord (using the specified store) */
  function setCoord(IStore _store, bytes32 key, uint256 coord) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((coord)));
  }

  /** Get index */
  function getIndex(bytes32 key) internal view returns (uint8 index) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get index (using the specified store) */
  function getIndex(IStore _store, bytes32 key) internal view returns (uint8 index) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set index */
  function setIndex(bytes32 key, uint8 index) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((index)));
  }

  /** Set index (using the specified store) */
  function setIndex(IStore _store, bytes32 key, uint8 index) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((index)));
  }

  /** Get tileType */
  function getTileType(bytes32 key) internal view returns (uint8 tileType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get tileType (using the specified store) */
  function getTileType(IStore _store, bytes32 key) internal view returns (uint8 tileType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set tileType */
  function setTileType(bytes32 key, uint8 tileType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((tileType)));
  }

  /** Set tileType (using the specified store) */
  function setTileType(IStore _store, bytes32 key, uint8 tileType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((tileType)));
  }

  /** Get tileX */
  function getTileX(bytes32 key) internal view returns (uint8 tileX) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 3);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get tileX (using the specified store) */
  function getTileX(IStore _store, bytes32 key) internal view returns (uint8 tileX) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 3);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set tileX */
  function setTileX(bytes32 key, uint8 tileX) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _keyTuple, 3, abi.encodePacked((tileX)));
  }

  /** Set tileX (using the specified store) */
  function setTileX(IStore _store, bytes32 key, uint8 tileX) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    _store.setField(_tableId, _keyTuple, 3, abi.encodePacked((tileX)));
  }

  /** Get tileY */
  function getTileY(bytes32 key) internal view returns (uint8 tileY) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 4);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get tileY (using the specified store) */
  function getTileY(IStore _store, bytes32 key) internal view returns (uint8 tileY) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 4);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set tileY */
  function setTileY(bytes32 key, uint8 tileY) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _keyTuple, 4, abi.encodePacked((tileY)));
  }

  /** Set tileY (using the specified store) */
  function setTileY(IStore _store, bytes32 key, uint8 tileY) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    _store.setField(_tableId, _keyTuple, 4, abi.encodePacked((tileY)));
  }

  /** Get gridX */
  function getGridX(bytes32 key) internal view returns (uint8 gridX) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 5);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get gridX (using the specified store) */
  function getGridX(IStore _store, bytes32 key) internal view returns (uint8 gridX) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 5);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set gridX */
  function setGridX(bytes32 key, uint8 gridX) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _keyTuple, 5, abi.encodePacked((gridX)));
  }

  /** Set gridX (using the specified store) */
  function setGridX(IStore _store, bytes32 key, uint8 gridX) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    _store.setField(_tableId, _keyTuple, 5, abi.encodePacked((gridX)));
  }

  /** Get gridY */
  function getGridY(bytes32 key) internal view returns (uint8 gridY) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 6);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get gridY (using the specified store) */
  function getGridY(IStore _store, bytes32 key) internal view returns (uint8 gridY) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 6);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set gridY */
  function setGridY(bytes32 key, uint8 gridY) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _keyTuple, 6, abi.encodePacked((gridY)));
  }

  /** Set gridY (using the specified store) */
  function setGridY(IStore _store, bytes32 key, uint8 gridY) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    _store.setField(_tableId, _keyTuple, 6, abi.encodePacked((gridY)));
  }

  /** Get the full data */
  function get(bytes32 key) internal view returns (TilesData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 key) internal view returns (TilesData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 key,
    uint256 coord,
    uint8 index,
    uint8 tileType,
    uint8 tileX,
    uint8 tileY,
    uint8 gridX,
    uint8 gridY
  ) internal {
    bytes memory _data = encode(coord, index, tileType, tileX, tileY, gridX, gridY);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 key,
    uint256 coord,
    uint8 index,
    uint8 tileType,
    uint8 tileX,
    uint8 tileY,
    uint8 gridX,
    uint8 gridY
  ) internal {
    bytes memory _data = encode(coord, index, tileType, tileX, tileY, gridX, gridY);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 key, TilesData memory _table) internal {
    set(key, _table.coord, _table.index, _table.tileType, _table.tileX, _table.tileY, _table.gridX, _table.gridY);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 key, TilesData memory _table) internal {
    set(
      _store,
      key,
      _table.coord,
      _table.index,
      _table.tileType,
      _table.tileX,
      _table.tileY,
      _table.gridX,
      _table.gridY
    );
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (TilesData memory _table) {
    _table.coord = (uint256(Bytes.slice32(_blob, 0)));

    _table.index = (uint8(Bytes.slice1(_blob, 32)));

    _table.tileType = (uint8(Bytes.slice1(_blob, 33)));

    _table.tileX = (uint8(Bytes.slice1(_blob, 34)));

    _table.tileY = (uint8(Bytes.slice1(_blob, 35)));

    _table.gridX = (uint8(Bytes.slice1(_blob, 36)));

    _table.gridY = (uint8(Bytes.slice1(_blob, 37)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    uint256 coord,
    uint8 index,
    uint8 tileType,
    uint8 tileX,
    uint8 tileY,
    uint8 gridX,
    uint8 gridY
  ) internal view returns (bytes memory) {
    return abi.encodePacked(coord, index, tileType, tileX, tileY, gridX, gridY);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 key) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 key) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 key) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32((key));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
