// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Token, TokenTableId } from "./tables/Token.sol";
import { Chamber, ChamberData, ChamberTableId } from "./tables/Chamber.sol";
import { ChamberMetadata, ChamberMetadataData, ChamberMetadataTableId } from "./tables/ChamberMetadata.sol";
import { Agent, AgentData, AgentTableId } from "./tables/Agent.sol";
import { Metadata, MetadataData, MetadataTableId } from "./tables/Metadata.sol";
import { Doors, DoorsData, DoorsTableId } from "./tables/Doors.sol";
import { Tiles, TilesData, TilesTableId } from "./tables/Tiles.sol";
import { Door, DoorTableId } from "./tables/Door.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Location, LocationData, LocationTableId } from "./tables/Location.sol";
import { Blocker, BlockerTableId } from "./tables/Blocker.sol";
