// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IChamberSystem {
  function tokenURI(uint256 coord) external returns (string memory);
}
