// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IDoorsSystem {
  function setDoor(uint256 coord, uint8 index, uint8 dir, bool locked) external;
}
