// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITilesSystem {
  function setTile(
    uint256 coord,
    uint8 index,
    uint8 tileType,
    uint8 tileX,
    uint8 tileY,
    uint8 gridX,
    uint8 gridY
  ) external;
}
