// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITokenSystem {
  function tokenIdToCoord(uint256 tokenId) external returns (uint256);
}
