// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITokenSystem {
  function set_tokenIdToCoord(uint256 tokenId, uint256 coord) external;
}
