// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Direction } from "./../Types.sol";

interface IPlayerSystem {
  function spawn(string memory name, int32 x, int32 y) external;

  function move(Direction direction) external;

  function goToPosition(bytes32 player, int32 x, int32 y) external;
}
