// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Direction } from "./../Types.sol";

interface IPlayerSystem {
  function spawnAtPosition(string memory name, int32 x, int32 y) external;

  function moveToDirection(Direction direction) external;

  function moveToPosition(int32 x, int32 y) external;
}
