// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IRealmSystem {
  function setRealm(uint256 coord) external;

  function setRealmMetadata(uint256 coord, string memory metadata) external;

  function setRealmProfileImage(uint256 coord, string memory url) external;
}
