// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITilesSystem {
  function setTile(uint8 terrain, uint8 tileType, int32 gridX, int32 gridY) external;
}
