// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IAgentSystem } from "./IAgentSystem.sol";
import { IChamberSystem } from "./IChamberSystem.sol";
import { IPlayerSystem } from "./IPlayerSystem.sol";
import { IRealmSystem } from "./IRealmSystem.sol";
import { ITileSystem } from "./ITileSystem.sol";
import { ITokenSystem } from "./ITokenSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, IAgentSystem, IChamberSystem, IPlayerSystem, IRealmSystem, ITileSystem, ITokenSystem {

}
