// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IAgentSystem } from "./IAgentSystem.sol";
import { IChamberSystem } from "./IChamberSystem.sol";
import { IDoorsSystem } from "./IDoorsSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { IPlayerSystem } from "./IPlayerSystem.sol";
import { ITilesSystem } from "./ITilesSystem.sol";
import { ITokenSystem } from "./ITokenSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  IAgentSystem,
  IChamberSystem,
  IDoorsSystem,
  IIncrementSystem,
  IPlayerSystem,
  ITilesSystem,
  ITokenSystem
{

}
