/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Counter: (() => {
      const tableId = new TableId("", "Counter");
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Token: (() => {
      const tableId = new TableId("", "Token");
      return defineComponent(
        world,
        {
          coord: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Chamber: (() => {
      const tableId = new TableId("", "Chamber");
      return defineComponent(
        world,
        {
          opener: RecsType.String,
          tokenId: RecsType.BigInt,
          seed: RecsType.BigInt,
          yonder: RecsType.Number,
          chapter: RecsType.Number,
          terrain: RecsType.Number,
          entryDir: RecsType.Number,
          gemPos: RecsType.Number,
          gemType: RecsType.Number,
          coins: RecsType.Number,
          worth: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
